config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root 'entries#index'
  resources :entries
end

app/models/admin.rb
# frozen_string_literal: true

class Admin < ApplicationRecord
  has_many :entries, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :username,
            presence: true,
            length: { minimum: 6 },
            uniqueness: { case_sensitive: false }
  validates :first_name, :last_name,
            presence: true,
            length: { in: 2..25 }

  def name
    first_name + ' ' + last_name
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
# frozen_string_literal: true

class Entry < ApplicationRecord
  CONTENT_LENGTH_MAX = 40_000
  IMAGE_SIZE_MAX = 5.megabytes

  belongs_to :admin

  has_attached_file :image,
                    styles: { medium: '800x500>' },
                    default_url: '/images/:style/missing.png'
  validates_attachment :image,
                       content_type: { content_type: ['image/jpeg', 'image/gif', 'image/png'] },
                       size: { in: 0..IMAGE_SIZE_MAX }

  validates :title, presence: true,
                    length: { in: 3..200 }
  validates :content, presence: true,
                      length: { in: 3..CONTENT_LENGTH_MAX }

  default_scope -> { order(created_at: :desc) }

  def author
    admin ? admin.name : 'Anonymous'
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :collection, :resource
  before_action :configure_permitted_params, if: :devise_controller?

  protected

  def configure_permitted_params
    keys = %i[username first_name last_name email]
    devise_parameter_sanitizer.permit(:sign_up, keys: keys)
  end
end

app/controllers/entries_controller.rb
# frozen_string_literal: true

class EntriesController < ApplicationController
  helper_method :entries, :entry
  attr_accessor :entries, :entry

  before_action :authenticate_admin!, except: %i[index show]

  def index
    @entries = Entry.page(params[:page]).per(4)
  end

  def new
    @entry = current_admin.entries.build
  end

  def create
    @entry = current_admin.entries.build(entry_params)
    if entry.save
      flash[:notice] = 'Your entry was created!'
      redirect_to entries_path
    else
      render :new
    end
  end

  def edit; end

  def update
    if entry.update_attributes(entry_params)
      flash[:notice] = 'Your entry was updated.'
      redirect_to entries_path
    else
      render :edit
    end
  end

  def show
    # Anyone should be able to see this, not just an admin
    @entry = Entry.where(id: params[:id]).first
  end

  def destroy
    if entry.destroy
      flash[:notice] = 'Your entry was destroyed.'
      redirect_to entries_path
    else
      flash[:alert] = 'There was an error :('
      redirect_to :back
    end
  end

  private

  def entry_params
    params.require(:entry).permit(:title, :content, :favorite, :image)
  end

  def entry
    @entry ||= current_admin.entries.where(id: params[:id]).first
  end

  def resource
    entry
  end

  def collection
    entries
  end
end

app/controllers/entry_controller.rb
class EntryController < ApplicationController

  helper_method :entries, :entry
  attr_accessor :entries, :entry

  def index
    @entries = Entry.all
  end

  def new
    entry = Entry.new
  end

  def create
    entry = Entry.new(entry_params)
    # entry.admin = current_user
    if entry.save
      flash[:success] = 'Your entry was created!'
      redirect_to :index
    else
      flash[:error] = 'There was an error :('
      render :new
    end
  end

  # edit
  # show
  # update
  # destroy

  private

  def entry_params
    params.require(:entry).permit(:title, :content, :favorite)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_entry.html.haml
.display-6
  = add_link ? link_to(ent.title, ent) : ent.title

%small.text-muted
  written by
  = ent.author

- if ent.image.present?
  = image_tag ent.image.url(:medium)

%p= simple_format(ent.content)

app/views/entries/_form.html.haml
= simple_form_for entry, url: path, method: method do |f|
  = f.input :title, placeholder: 'Title', label: false
  = f.input :image, as: :file, placeholder: 'Choose image'
  = f.input :content, as: :text, placeholder: 'Content', label: false, input_html: { rows: 20 }

  = f.submit submit, class: "btn btn-primary"

app/views/entries/edit.html.haml
.form
  %h3.display-6
    Edit Entry

  = render 'shared/errors'
  = render 'form', path: entry_url(entry.id), submit: "Update this Entry", method: :put

app/views/entries/index.html.haml
.blog
  .blog-title
    %h1.display-3
      A Student Notebook
    - if admin_signed_in?
      = link_to "New Entry", new_entry_url, class: 'btn btn-outline-primary'

  - entries.each do |ent|
    %hr.my-4
    = render 'entry', ent: ent, add_link: true

  %hr.my-4

  .pagination= paginate entries
  = page_entries_info entries

app/views/entries/new.html.haml
.form
  %h3.display-6
    New Entry

  = render 'shared/errors'
  = render 'form', path: entries_path, method: :post, submit: 'Share this with the world'

app/views/entries/show.html.haml
.blog
  = render 'entry', ent: entry, add_link: false

  - if admin_signed_in? && current_admin == entry.admin
    .row
      = link_to "Edit", edit_entry_path(entry.id), class: 'btn btn-outline-info half-width'
      = link_to "Destroy", entry_path(entry.id), method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-outline-danger half-width'

app/views/entry/new.html.erb
<h3>
  A New Eloquent Entry
</h3>

<%= simple_form_for :entry, url: entry_index_path, html: { class: 'form-horizontal' } do |f| %>
  <%= f.input :title, placeholder: 'A humble  title' %>
  <%= f.input :content, as: :text, placeholder: 'Eloquent thoughts', input_html: { rows: 15 } %>

  <%= f.submit "Share this with the world", class: "btn btn-primary" %>
<% end %>

app/views/layouts/_nav.html.haml
.col-md-4
  = link_to "Blog", root_url, title: "A Student's Notebook"
  = link_to "Code Repos", 'https://harishsr.com', title: 'Code Repositories', target: "_blank"
  = link_to "GitHub", 'http://github.com/harishsr', title: 'GitHub Profile', target: "_blank"
  = link_to "LinkedIn", 'https://linkedin.com/in/harishsr', title: 'LinkedIn Profile', target: "_blank"

.col-md-4
.col-md-4
  - if admin_signed_in?
    Welcome, 
    = current_admin.username
    = link_to "Sign off", destroy_admin_session_url, title: "Sign off", method: :delete
  
  - else
    = link_to "Sign in", new_admin_session_url, title: "Sign in"

app/views/layouts/_nav1.html.haml
.container.fixed-top.nav1
  .row
    .col-md-4
      = link_to "Blog", root_url, title: "A Student's Notebook"
      = link_to "Code Repos", 'https://harishsr.com', title: 'Code Repositories'
      = link_to "GitHub", 'http://github.com/harishsr', title: 'GitHub Profile'
      = link_to "LinkedIn", 'https://linkedin.com/in/harishsr', title: 'LinkedIn Profile'

    .col-md-4
    .col-md-4
      - if admin_signed_in?
        Welcome, 
        = current_admin.username
        = link_to "Sign off", destroy_admin_session_url, title: "Sign off", method: :delete
      
      - else
        = link_to "Sign in", new_admin_session_url, title: "Sign in"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Harish R
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .container.nav.fixed-top
      = render 'layouts/nav'

    .container
      .col-md-2

      .col-md-8
        .row
          - if notice
            %div{class: "alert alert-info wide"}
              = notice
          - if alert
            %div{class: "alert alert-danger wide"}
              = alert
        .row
          = yield

      .col-md-2

app/views/shared/_errors.html.haml
- if resource.errors.any?
  .alert.alert-danger
    %h3
      There are 
      =pluralize resource.errors.count, "error"
      on this page
    %ul
      - resource.errors.full_messages.each do |message|
        %li= message